model:
  name: openai/clip-vit-large-patch14-336
  model_config:
    vision_config:
      variant: resnet50
  prompt_learning: False
  prompt_from_visual_tokens: False
  auxiliary_model: False
  m2_loss: False

dataset:
  dataset_path: /home/dslisleedh/NLPProject/hpitp_dataset
  train_ratio: 0.8
  permute_colors: False
  # img_size: 224
  img_size: 224

train:
  device: cuda:0
  seed: 42
  batch_size: 8
  num_workers: 4
  epochs: 50

optimizer:
  name: AdaBelief
  lr: !!float 2e-5
  rectify: False

scheduler: 
  name: LinearWarmupLinearDecayLR
  warmup_iter: 3
  max_iter: ${train.epochs}
  eta_min: !!float 1e-3
  start_factor: 1e-3

early_stopping:
  criterion: recall_at_5
  patience: 5
  maximize: True

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# hydra and directory-related settings.
log_prefix: ./train_logs
hydra:
  run:
    dir: ${log_prefix}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${log_prefix}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ''

  job:
    chdir: True
    env_set:
      CUDA_VISIBLE_DEVICES: 0
      # API_KEY: 1234.....